# Per https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:

# Alpine Linux

- package-ecosystem: docker
  directory: "11/alpine/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

- package-ecosystem: docker
  directory: "8/alpine/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

# AlmaLinux

- package-ecosystem: docker
  directory: "11/almalinux/almalinux8/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - saper
  - slide
  labels:
  - dependencies

# CentOS Linux

- package-ecosystem: docker
  directory: "8/centos/centos7/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - slide
  labels:
  - dependencies

# Debian Linux

- package-ecosystem: docker
  directory: "11/debian/bullseye/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

- package-ecosystem: docker
  directory: "11/debian/bullseye-slim/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

- package-ecosystem: docker
  directory: "8/debian/bullseye/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

- package-ecosystem: docker
  directory: "8/debian/bullseye-slim/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - MarkEWaite
  - slide
  labels:
  - dependencies

# RHEL UBI

- package-ecosystem: docker
  directory: "11/rhel/ubi8/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
    - olivergondza
    - slide
  labels:
    - dependencies

# Windows

- package-ecosystem: docker
  directory: "11/windows/windowsservercore-2019/hotspot"
  schedule:
    interval: weekly
  open-pull-requests-limit: 2
  target-branch: master
  reviewers:
  - slide
  labels:
  - dependencies
