version: '3.8'

services:
  jenkins:
    container_name: ${APP_CONTAINER_NAME}
    image: jenkins/jenkins:${APP_VERSION}
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    user: root
    restart: always
    ports:
      - "50000:50000"
      - "${APP_PORT}:8080"
    volumes:
      - ${VOLUMES_PATH_PREFIX}/data/jenkins:/var/jenkins_home

networks:
  default:
      name: ${APP_NETWORK}
